# SPDX-FileCopyrightText: James Turner <james@flightgear.org>
#
# SPDX-License-Identifier: GPL-2.0

variables:
  BUILD_DIR: "$CI_PROJECT_DIR/build"
  PREFIX_DIR: "$CI_PROJECT_DIR/simgear-dist"
  # create a root dir *above* the Simgear checkout, otherwise CMake
  # complains about INTERFACE_INCLUDE_DIRECTORIES being the source dir
  WIN_FG_DIR: $CI_BUILDS_DIR\flightgear
  MAC_IMAGE: macos-14-xcode-15
  OSG_REF: fgfs-osg-36-2
  BRANCH_REF: next





macos-build:
  stage: build
  tags:
    - saas-macos-medium-m1
  image: $MAC_IMAGE
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  before_script:
      - export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
      - export HOMEBREW_NO_INSTALL_CLEANUP=1
      - brew install ninja cmake boost
  script:
    - cmake -B $BUILD_DIR -S $CI_PROJECT_DIR -G Ninja 
      --fresh
      -D CMAKE_BUILD_TYPE=RelWithDebInfo 
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D CMAKE_PREFIX_PATH=$CI_PROJECT_DIR/osg-dist
      -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
      -D ENABLE_TESTS=OFF
      -D ENABLE_SIMD:BOOL=OFF

    - cmake --build $BUILD_DIR
    - cmake --build $BUILD_DIR --target install
  needs:
    - project: flightgear/openscenegraph
      job: macos-build
      ref: $OSG_REF
      artifacts: true
  artifacts:
    paths:
      - $PREFIX_DIR
  cache:
    paths:
      - $BUILD_DIR

